version: "3.9"
services:
    postgres:
        container_name: database
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=abcd1234
            - POSTGRES_USER=devdb
    redis:
        container_name: redis
        image: redis
        command: redis-server --requirepass yourpassword
        environment:
            - REDIS_PASSWORD=abcd1234

networks:
    default:
        external: true
        name: devnet
