version: "3.9"
services:
    backends:
        container_name: backends
        image: bukanebi/backends:dev
        ports:
            - 9000-9002:9000
        networks: 
            - devnet

networks:
    default:
        external: true
        name: devnet
