version: "3.9"
services:
    backends:
        container_name: backends
        image: bukanebi/backends:dev
        ports:
            - 9000-9002:9000
        networks:
            - devnet
        deploy:
            mode: replicated
            replicas: 3

networks:
    devnet:
        external: true
